/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ntthanh.drink_store.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import com.ntthanh.drink_store.model.OrderDrink;
import com.ntthanh.drink_store.service.OrderDrinkService;
import com.ntthanh.drink_store.service.OrderDrinkServiceUtil;
import com.ntthanh.drink_store.service.persistence.DrinkPersistence;
import com.ntthanh.drink_store.service.persistence.OrderDetailPersistence;
import com.ntthanh.drink_store.service.persistence.OrderDrinkPersistence;
import com.ntthanh.drink_store.service.persistence.TableDrinkPersistence;

import java.lang.reflect.Field;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the order drink remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.ntthanh.drink_store.service.impl.OrderDrinkServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.ntthanh.drink_store.service.impl.OrderDrinkServiceImpl
 * @generated
 */
public abstract class OrderDrinkServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, IdentifiableOSGiService, OrderDrinkService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>OrderDrinkService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>OrderDrinkServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		_setServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			OrderDrinkService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		orderDrinkService = (OrderDrinkService)aopProxy;

		_setServiceUtilService(orderDrinkService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return OrderDrinkService.class.getName();
	}

	protected Class<?> getModelClass() {
		return OrderDrink.class;
	}

	protected String getModelClassName() {
		return OrderDrink.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = orderDrinkPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setServiceUtilService(OrderDrinkService orderDrinkService) {
		try {
			Field field = OrderDrinkServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, orderDrinkService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected DrinkPersistence drinkPersistence;

	@Reference
	protected OrderDetailPersistence orderDetailPersistence;

	@Reference
	protected com.ntthanh.drink_store.service.OrderDrinkLocalService
		orderDrinkLocalService;

	protected OrderDrinkService orderDrinkService;

	@Reference
	protected OrderDrinkPersistence orderDrinkPersistence;

	@Reference
	protected TableDrinkPersistence tableDrinkPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	private static final Log _log = LogFactoryUtil.getLog(
		OrderDrinkServiceBaseImpl.class);

}