/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ntthanh.drink_store.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.ntthanh.drink_store.model.Drink;
import com.ntthanh.drink_store.model.DrinkModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Drink service. Represents a row in the &quot;DRINK_STORE_Drink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DrinkModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DrinkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DrinkImpl
 * @generated
 */
@JSON(strict = true)
public class DrinkModelImpl extends BaseModelImpl<Drink> implements DrinkModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a drink model instance should use the <code>Drink</code> interface instead.
	 */
	public static final String TABLE_NAME = "DRINK_STORE_Drink";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"drinkName", Types.VARCHAR},
		{"category", Types.VARCHAR}, {"price", Types.DOUBLE},
		{"imageUrl", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("drinkName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("category", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("price", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("imageUrl", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table DRINK_STORE_Drink (id_ LONG not null primary key,drinkName VARCHAR(75) null,category VARCHAR(75) null,price DOUBLE,imageUrl VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table DRINK_STORE_Drink";

	public static final String ORDER_BY_JPQL = " ORDER BY drink.drinkName ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY DRINK_STORE_Drink.drinkName ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CATEGORY_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PRICE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DRINKNAME_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public DrinkModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Drink.class;
	}

	@Override
	public String getModelClassName() {
		return Drink.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Drink, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Drink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Drink, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Drink)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Drink, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Drink, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Drink)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Drink, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Drink, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Drink, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Drink, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Drink, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Drink, Object>>();
		Map<String, BiConsumer<Drink, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Drink, ?>>();

		attributeGetterFunctions.put("id", Drink::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<Drink, Long>)Drink::setId);
		attributeGetterFunctions.put("drinkName", Drink::getDrinkName);
		attributeSetterBiConsumers.put(
			"drinkName", (BiConsumer<Drink, String>)Drink::setDrinkName);
		attributeGetterFunctions.put("category", Drink::getCategory);
		attributeSetterBiConsumers.put(
			"category", (BiConsumer<Drink, String>)Drink::setCategory);
		attributeGetterFunctions.put("price", Drink::getPrice);
		attributeSetterBiConsumers.put(
			"price", (BiConsumer<Drink, Double>)Drink::setPrice);
		attributeGetterFunctions.put("imageUrl", Drink::getImageUrl);
		attributeSetterBiConsumers.put(
			"imageUrl", (BiConsumer<Drink, String>)Drink::setImageUrl);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public String getDrinkName() {
		if (_drinkName == null) {
			return "";
		}
		else {
			return _drinkName;
		}
	}

	@Override
	public void setDrinkName(String drinkName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_drinkName = drinkName;
	}

	@JSON
	@Override
	public String getCategory() {
		if (_category == null) {
			return "";
		}
		else {
			return _category;
		}
	}

	@Override
	public void setCategory(String category) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_category = category;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCategory() {
		return getColumnOriginalValue("category");
	}

	@JSON
	@Override
	public double getPrice() {
		return _price;
	}

	@Override
	public void setPrice(double price) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_price = price;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public double getOriginalPrice() {
		return GetterUtil.getDouble(
			this.<Double>getColumnOriginalValue("price"));
	}

	@JSON
	@Override
	public String getImageUrl() {
		if (_imageUrl == null) {
			return "";
		}
		else {
			return _imageUrl;
		}
	}

	@Override
	public void setImageUrl(String imageUrl) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_imageUrl = imageUrl;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Drink.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Drink toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Drink>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DrinkImpl drinkImpl = new DrinkImpl();

		drinkImpl.setId(getId());
		drinkImpl.setDrinkName(getDrinkName());
		drinkImpl.setCategory(getCategory());
		drinkImpl.setPrice(getPrice());
		drinkImpl.setImageUrl(getImageUrl());

		drinkImpl.resetOriginalValues();

		return drinkImpl;
	}

	@Override
	public Drink cloneWithOriginalValues() {
		DrinkImpl drinkImpl = new DrinkImpl();

		drinkImpl.setId(this.<Long>getColumnOriginalValue("id_"));
		drinkImpl.setDrinkName(
			this.<String>getColumnOriginalValue("drinkName"));
		drinkImpl.setCategory(this.<String>getColumnOriginalValue("category"));
		drinkImpl.setPrice(this.<Double>getColumnOriginalValue("price"));
		drinkImpl.setImageUrl(this.<String>getColumnOriginalValue("imageUrl"));

		return drinkImpl;
	}

	@Override
	public int compareTo(Drink drink) {
		int value = 0;

		value = getDrinkName().compareTo(drink.getDrinkName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Drink)) {
			return false;
		}

		Drink drink = (Drink)object;

		long primaryKey = drink.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Drink> toCacheModel() {
		DrinkCacheModel drinkCacheModel = new DrinkCacheModel();

		drinkCacheModel.id = getId();

		drinkCacheModel.drinkName = getDrinkName();

		String drinkName = drinkCacheModel.drinkName;

		if ((drinkName != null) && (drinkName.length() == 0)) {
			drinkCacheModel.drinkName = null;
		}

		drinkCacheModel.category = getCategory();

		String category = drinkCacheModel.category;

		if ((category != null) && (category.length() == 0)) {
			drinkCacheModel.category = null;
		}

		drinkCacheModel.price = getPrice();

		drinkCacheModel.imageUrl = getImageUrl();

		String imageUrl = drinkCacheModel.imageUrl;

		if ((imageUrl != null) && (imageUrl.length() == 0)) {
			drinkCacheModel.imageUrl = null;
		}

		return drinkCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Drink, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Drink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Drink, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Drink)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Drink>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Drink.class, ModelWrapper.class);

	}

	private long _id;
	private String _drinkName;
	private String _category;
	private double _price;
	private String _imageUrl;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Drink, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Drink)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("drinkName", _drinkName);
		_columnOriginalValues.put("category", _category);
		_columnOriginalValues.put("price", _price);
		_columnOriginalValues.put("imageUrl", _imageUrl);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("drinkName", 2L);

		columnBitmasks.put("category", 4L);

		columnBitmasks.put("price", 8L);

		columnBitmasks.put("imageUrl", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Drink _escapedModel;

}