/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ntthanh.drink_store.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.ntthanh.drink_store.model.TableDrink;
import com.ntthanh.drink_store.model.TableDrinkModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TableDrink service. Represents a row in the &quot;DRINK_STORE_TableDrink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TableDrinkModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TableDrinkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TableDrinkImpl
 * @generated
 */
@JSON(strict = true)
public class TableDrinkModelImpl
	extends BaseModelImpl<TableDrink> implements TableDrinkModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a table drink model instance should use the <code>TableDrink</code> interface instead.
	 */
	public static final String TABLE_NAME = "DRINK_STORE_TableDrink";

	public static final Object[][] TABLE_COLUMNS = {
		{"tableDrinkId", Types.BIGINT}, {"tableNumber", Types.INTEGER},
		{"seats", Types.INTEGER}, {"status", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("tableDrinkId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("tableNumber", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("seats", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table DRINK_STORE_TableDrink (tableDrinkId LONG not null primary key,tableNumber INTEGER,seats INTEGER,status VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table DRINK_STORE_TableDrink";

	public static final String ORDER_BY_JPQL =
		" ORDER BY tableDrink.tableNumber ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY DRINK_STORE_TableDrink.tableNumber ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SEATS_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TABLEDRINKID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TABLENUMBER_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public TableDrinkModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _tableDrinkId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTableDrinkId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _tableDrinkId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TableDrink.class;
	}

	@Override
	public String getModelClassName() {
		return TableDrink.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TableDrink, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TableDrink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TableDrink, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((TableDrink)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TableDrink, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TableDrink, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TableDrink)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TableDrink, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TableDrink, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<TableDrink, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TableDrink, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TableDrink, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<TableDrink, Object>>();
		Map<String, BiConsumer<TableDrink, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<TableDrink, ?>>();

		attributeGetterFunctions.put(
			"tableDrinkId", TableDrink::getTableDrinkId);
		attributeSetterBiConsumers.put(
			"tableDrinkId",
			(BiConsumer<TableDrink, Long>)TableDrink::setTableDrinkId);
		attributeGetterFunctions.put("tableNumber", TableDrink::getTableNumber);
		attributeSetterBiConsumers.put(
			"tableNumber",
			(BiConsumer<TableDrink, Integer>)TableDrink::setTableNumber);
		attributeGetterFunctions.put("seats", TableDrink::getSeats);
		attributeSetterBiConsumers.put(
			"seats", (BiConsumer<TableDrink, Integer>)TableDrink::setSeats);
		attributeGetterFunctions.put("status", TableDrink::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<TableDrink, String>)TableDrink::setStatus);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getTableDrinkId() {
		return _tableDrinkId;
	}

	@Override
	public void setTableDrinkId(long tableDrinkId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tableDrinkId = tableDrinkId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalTableDrinkId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("tableDrinkId"));
	}

	@JSON
	@Override
	public int getTableNumber() {
		return _tableNumber;
	}

	@Override
	public void setTableNumber(int tableNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tableNumber = tableNumber;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalTableNumber() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("tableNumber"));
	}

	@JSON
	@Override
	public int getSeats() {
		return _seats;
	}

	@Override
	public void setSeats(int seats) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_seats = seats;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalSeats() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("seats"));
	}

	@JSON
	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalStatus() {
		return getColumnOriginalValue("status");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, TableDrink.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TableDrink toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TableDrink>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TableDrinkImpl tableDrinkImpl = new TableDrinkImpl();

		tableDrinkImpl.setTableDrinkId(getTableDrinkId());
		tableDrinkImpl.setTableNumber(getTableNumber());
		tableDrinkImpl.setSeats(getSeats());
		tableDrinkImpl.setStatus(getStatus());

		tableDrinkImpl.resetOriginalValues();

		return tableDrinkImpl;
	}

	@Override
	public TableDrink cloneWithOriginalValues() {
		TableDrinkImpl tableDrinkImpl = new TableDrinkImpl();

		tableDrinkImpl.setTableDrinkId(
			this.<Long>getColumnOriginalValue("tableDrinkId"));
		tableDrinkImpl.setTableNumber(
			this.<Integer>getColumnOriginalValue("tableNumber"));
		tableDrinkImpl.setSeats(this.<Integer>getColumnOriginalValue("seats"));
		tableDrinkImpl.setStatus(this.<String>getColumnOriginalValue("status"));

		return tableDrinkImpl;
	}

	@Override
	public int compareTo(TableDrink tableDrink) {
		int value = 0;

		if (getTableNumber() < tableDrink.getTableNumber()) {
			value = -1;
		}
		else if (getTableNumber() > tableDrink.getTableNumber()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TableDrink)) {
			return false;
		}

		TableDrink tableDrink = (TableDrink)object;

		long primaryKey = tableDrink.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TableDrink> toCacheModel() {
		TableDrinkCacheModel tableDrinkCacheModel = new TableDrinkCacheModel();

		tableDrinkCacheModel.tableDrinkId = getTableDrinkId();

		tableDrinkCacheModel.tableNumber = getTableNumber();

		tableDrinkCacheModel.seats = getSeats();

		tableDrinkCacheModel.status = getStatus();

		String status = tableDrinkCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			tableDrinkCacheModel.status = null;
		}

		return tableDrinkCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TableDrink, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TableDrink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TableDrink, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((TableDrink)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TableDrink>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					TableDrink.class, ModelWrapper.class);

	}

	private long _tableDrinkId;
	private int _tableNumber;
	private int _seats;
	private String _status;

	public <T> T getColumnValue(String columnName) {
		Function<TableDrink, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((TableDrink)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("tableDrinkId", _tableDrinkId);
		_columnOriginalValues.put("tableNumber", _tableNumber);
		_columnOriginalValues.put("seats", _seats);
		_columnOriginalValues.put("status", _status);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("tableDrinkId", 1L);

		columnBitmasks.put("tableNumber", 2L);

		columnBitmasks.put("seats", 4L);

		columnBitmasks.put("status", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private TableDrink _escapedModel;

}