/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ntthanh.drink_store.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Drink service. Represents a row in the &quot;DRINK_STORE_Drink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ntthanh.drink_store.model.impl.DrinkModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ntthanh.drink_store.model.impl.DrinkImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Drink
 * @generated
 */
@ProviderType
public interface DrinkModel extends BaseModel<Drink> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a drink model instance should use the {@link Drink} interface instead.
	 */

	/**
	 * Returns the primary key of this drink.
	 *
	 * @return the primary key of this drink
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this drink.
	 *
	 * @param primaryKey the primary key of this drink
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this drink.
	 *
	 * @return the ID of this drink
	 */
	public long getId();

	/**
	 * Sets the ID of this drink.
	 *
	 * @param id the ID of this drink
	 */
	public void setId(long id);

	/**
	 * Returns the drink name of this drink.
	 *
	 * @return the drink name of this drink
	 */
	@AutoEscape
	public String getDrinkName();

	/**
	 * Sets the drink name of this drink.
	 *
	 * @param drinkName the drink name of this drink
	 */
	public void setDrinkName(String drinkName);

	/**
	 * Returns the category of this drink.
	 *
	 * @return the category of this drink
	 */
	@AutoEscape
	public String getCategory();

	/**
	 * Sets the category of this drink.
	 *
	 * @param category the category of this drink
	 */
	public void setCategory(String category);

	/**
	 * Returns the price of this drink.
	 *
	 * @return the price of this drink
	 */
	public double getPrice();

	/**
	 * Sets the price of this drink.
	 *
	 * @param price the price of this drink
	 */
	public void setPrice(double price);

	/**
	 * Returns the image url of this drink.
	 *
	 * @return the image url of this drink
	 */
	@AutoEscape
	public String getImageUrl();

	/**
	 * Sets the image url of this drink.
	 *
	 * @param imageUrl the image url of this drink
	 */
	public void setImageUrl(String imageUrl);

	@Override
	public Drink cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}