/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ntthanh.drink_store.model;

import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the OrderDrink service. Represents a row in the &quot;DRINK_STORE_OrderDrink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ntthanh.drink_store.model.impl.OrderDrinkModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ntthanh.drink_store.model.impl.OrderDrinkImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OrderDrink
 * @generated
 */
@ProviderType
public interface OrderDrinkModel extends BaseModel<OrderDrink> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a order drink model instance should use the {@link OrderDrink} interface instead.
	 */

	/**
	 * Returns the primary key of this order drink.
	 *
	 * @return the primary key of this order drink
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this order drink.
	 *
	 * @param primaryKey the primary key of this order drink
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this order drink.
	 *
	 * @return the ID of this order drink
	 */
	public long getId();

	/**
	 * Sets the ID of this order drink.
	 *
	 * @param id the ID of this order drink
	 */
	public void setId(long id);

	/**
	 * Returns the table ID of this order drink.
	 *
	 * @return the table ID of this order drink
	 */
	public long getTableId();

	/**
	 * Sets the table ID of this order drink.
	 *
	 * @param tableId the table ID of this order drink
	 */
	public void setTableId(long tableId);

	/**
	 * Returns the total amount of this order drink.
	 *
	 * @return the total amount of this order drink
	 */
	public double getTotalAmount();

	/**
	 * Sets the total amount of this order drink.
	 *
	 * @param totalAmount the total amount of this order drink
	 */
	public void setTotalAmount(double totalAmount);

	/**
	 * Returns the order date of this order drink.
	 *
	 * @return the order date of this order drink
	 */
	public Date getOrderDate();

	/**
	 * Sets the order date of this order drink.
	 *
	 * @param orderDate the order date of this order drink
	 */
	public void setOrderDate(Date orderDate);

	/**
	 * Returns the paid of this order drink.
	 *
	 * @return the paid of this order drink
	 */
	public boolean getPaid();

	/**
	 * Returns <code>true</code> if this order drink is paid.
	 *
	 * @return <code>true</code> if this order drink is paid; <code>false</code> otherwise
	 */
	public boolean isPaid();

	/**
	 * Sets whether this order drink is paid.
	 *
	 * @param paid the paid of this order drink
	 */
	public void setPaid(boolean paid);

	@Override
	public OrderDrink cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}