/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ntthanh.drink_store.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TableDrink service. Represents a row in the &quot;DRINK_STORE_TableDrink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ntthanh.drink_store.model.impl.TableDrinkModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ntthanh.drink_store.model.impl.TableDrinkImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TableDrink
 * @generated
 */
@ProviderType
public interface TableDrinkModel extends BaseModel<TableDrink> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a table drink model instance should use the {@link TableDrink} interface instead.
	 */

	/**
	 * Returns the primary key of this table drink.
	 *
	 * @return the primary key of this table drink
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this table drink.
	 *
	 * @param primaryKey the primary key of this table drink
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the table drink ID of this table drink.
	 *
	 * @return the table drink ID of this table drink
	 */
	public long getTableDrinkId();

	/**
	 * Sets the table drink ID of this table drink.
	 *
	 * @param tableDrinkId the table drink ID of this table drink
	 */
	public void setTableDrinkId(long tableDrinkId);

	/**
	 * Returns the table number of this table drink.
	 *
	 * @return the table number of this table drink
	 */
	public int getTableNumber();

	/**
	 * Sets the table number of this table drink.
	 *
	 * @param tableNumber the table number of this table drink
	 */
	public void setTableNumber(int tableNumber);

	/**
	 * Returns the seats of this table drink.
	 *
	 * @return the seats of this table drink
	 */
	public int getSeats();

	/**
	 * Sets the seats of this table drink.
	 *
	 * @param seats the seats of this table drink
	 */
	public void setSeats(int seats);

	/**
	 * Returns the status of this table drink.
	 *
	 * @return the status of this table drink
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this table drink.
	 *
	 * @param status the status of this table drink
	 */
	public void setStatus(String status);

	@Override
	public TableDrink cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}